server:
  port: 8070
spring:
  application:
    name: redis-custom-serializer
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    baggage:
      remote-fields: app-route
      correlation-enabled: true
      correlation-fields: app-route


logging:
  level:
    com:
      turkcell: trace
    org:
      springframework.data: debug


redis:
  server:
    address: localhost
    port: 55000
    username: default
    cluster:
      nodes:
    password: ${REDIS_PASSWORD:redispw}
    environment: live


management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure.include: health,info




